<template>
  <nav>
    <ul>
      <!-- Use case c2a: Use the routes configured in main.js -->
      <li><router-link v-bind:to="'/'">Home</router-link></li>
      <li><router-link v-bind:to="'/about'">About</router-link></li>
    </ul>
    <ul>
      <!-- Entity relationships c7: Add login and register links-->
      <li v-if="loggedIn"><a @click.prevent="logout">Logout</a></li>
      <li v-else><router-link v-bind:to="'/login'">Login</router-link></li>
      <li><router-link v-bind:to="'/register'">Register</router-link></li>
    </ul>
  </nav>
</template>

<script>
import { EventBus } from '../event-bus';
export default {
  name: "MyHeader",
  data: function() {
    return {
      loggedIn: false
    };
  },
  methods: {
    // Use case c2a: Get the articles from the external API.
    logout: function(e) {
      e.preventDefault();
      EventBus.$emit('$loggedIn', false);
      localStorage.loggedIn = false;
      this.$router.push({ path: "/login" });
    },
    // Entity relationships c7: This will get called whenever the "$loggedIn" event is emitted
    setLoggedIn: function(loggedIn) {
      this.loggedIn = loggedIn;
    }
  },
  created: function() {
    this.loggedIn = localStorage.loggedIn == true;
    // Use case c3: Get the articles on creation of this component.
    EventBus.$on('$loggedIn', this.setLoggedIn);
  }
};
</script>

<style scoped>
/* Use case c2a: A class called "router-link-exact-active" will be auto-magically generated by Vue for the active
router-link */
.router-link-exact-active {
  font-weight: bold;
}
</style>
