<template>
  <nav>
    <ul>
      <!-- Use case c2: Use the routes configured in main.js -->
      <li><router-link v-bind:to="'/'">Home</router-link></li>
      <li><router-link v-bind:to="'/about'">About</router-link></li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: "MyHeader"
};
</script>

<style scoped>
/* Use case c2: A class called "router-link-exact-active" will be auto-magically generated by Vue for the active
router-link */
.router-link-exact-active {
  font-weight: bold;
}
</style>
